version: '3.8'
services:
  mongo:
    container_name: 'mongo'
    image: mongo:7.0.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
    restart: unless-stopped
